title: Jekyll Theme Docs
description: A documentation theme for Github Pages

permalink: pretty

search_enabled: true
auto_page_title: true

mermaid_enabled: true
mermaid_theme: forest

google_analytics: G-L24NDYGW09
google_verify: x76CJs4mUTH2_rQAC2Qnp6zvg_aLuWIWdd1o4o7iPIU

sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

exclude:
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .prettierrc
  - .prettierignore
  - .tool-versions
  - Gemfile
  - LICENSE*
  - node_modules
  - package.json
  - package-lock.json
  - README*
  - '*.gemspec'
  - '*.config.js'

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: default
