title: Jekyll Theme Docs
remote_theme: devexps/jekyll-theme-docs@main

baseurl: /jekyll-theme-docs

search_enabled: true
auto_page_title: true

google_analytics: G-L24NDYGW09
google_verify: x76CJs4mUTH2_rQAC2Qnp6zvg_aLuWIWdd1o4o7iPIU

sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development
